# Generated by Django 5.0.6 on 2026-05-27 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_card_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Номер читацького квитка')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, verbose_name='Адреса')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Дата реєстрації')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокований')),
                ('notes', models.TextField(blank=True, verbose_name='Нотатки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reader_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Читач',
                'verbose_name_plural': 'Читачі',
                'ordering': ['user__last_name', 'user__first_name'],
                'permissions': [('can_manage_readers', 'Може керувати читачами'), ('can_view_all_loans', 'Може переглядати всі позики')],
            },
        ),
    ]
