# Generated by Django 5.0.6 on 2026-05-28 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='notes',
        ),
    ]
