# Generated by Django 5.0.6 on 2026-05-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True, verbose_name='ISBN'),
        ),
    ]
