# Generated by Django 5.0.6 on 2026-05-27 08:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('readers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата видачі')),
                ('due_date', models.DateField(verbose_name='Дата повернення')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Фактична дата повернення')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('returned', 'Повернена'), ('overdue', 'Прострочена')], default='active', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Нотатки')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='books.book', verbose_name='Книга')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_loans', to=settings.AUTH_USER_MODEL, verbose_name='Видав')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='readers.reader', verbose_name='Читач')),
            ],
            options={
                'verbose_name': 'Позика',
                'verbose_name_plural': 'Позики',
                'ordering': ['-loan_date'],
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сума штрафу')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Сплачено')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Дата сплати')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fine', to='loans.loan', verbose_name='Позика')),
            ],
            options={
                'verbose_name': 'Штраф',
                'verbose_name_plural': 'Штрафи',
                'ordering': ['-created_at'],
            },
        ),
    ]
